### ISSUE TITLE
code review :)

### ISSUE THREAD

**Issue by Rokatoka** [Rrre-Gina/astro#1]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/script.js#L24

второй setTimeout лучше вынести в отдельную функцию чтобы читалось понятнее, можешь как раз попробовать использовать async/await https://learn.javascript.ru/async-await

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/index.html#L80 посмотри как работают async/defer у тегов <script> https://learn.javascript.ru/script-async-defer ты можешь поставить скрипт в начале файла чтобы он загрузился но начал использоваться когда страница будет готова

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/index.html#L65 
.footer__icons, .footer__phone, .footer__mail можно сделать все в один класс (например .footer__row) у них стили почти одинаковы и вместо каждому добавлять margin-bottom можно добавть :last-of-type https://developer.mozilla.org/ru/docs/Web/CSS/:last-of-type

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/index.html#L25 может хэдер сделать position: sticky? чтоб всегда видно было

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/css/style.css#L242 как мне говорили stacking context лучше избегать по возможности) https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/css/style.css#L108 просто margin-left: auto

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/css/style.css#L90 тоже из того что мне советовали: все величины в css старайся задавать кратно 4 (12, 16, 28) так будет визуально более ровно выглядеть

**Comment by Kuralbaev** [comment]
согласен :D

**Comment by Rrre-Gina** [comment]
> https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/script.js#L24
> 
> второй setTimeout лучше вынести в отдельную функцию чтобы читалось понятнее, можешь как раз попробовать использовать async/await https://learn.javascript.ru/async-await

можно ли использовать async/await в таком виде ? будет ли это корректно ?
![Uploading image.png…]()
если не загрузилось, то вот https://photo-screen.ru/i/Aeh8TdcrZ

**Comment by Rrre-Gina** [comment]
> https://github.com/Rrre-Gina/astro/blob/e9b88fb0ef8ab605ab3b95cf671b9bc13c8a5dd9/css/style.css#L242
> 
> как мне говорили stacking context лучше избегать по возможности) https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

нашла способ избежать в данном случае использование z-index для прелоадера, поставив его в самом низу страницы.

Но так как мы для хэдера указываем position: sticly, приходится для него указать z-index: 1, потому что на странице несколько элементов с абсолютным и относительным позиционированием и кнопка в хэдере неактивна в таких секциях. А так как мы указали для  хэдера z-index:1, он становится виден во время загрузки страницы поверх прелоадера. 
(можно поправить это через скрипт, чтобы он не отображался во время загрузки, но для хэдера, кажется, все равно придется оставить z-index, чтобы кнопка была активной на всей странице)

как лучше оставить ? :D 
1) чтобы z-index был и у хэдера и у прелоадера
2) оставть только у хэдера и скрывать его во время загрузки с помощью скрипта 
3) или есть еще какой-нибудь способ ?)

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/issues/1#issuecomment-1112113150

```
const loaded = () => {
	return new Promise((resolve) => {
  	    setTimeout(() => {
    	        document.body.classList.add('loaded');
                document.body.classList.remove('loaded_hiding');
                resolve();
            }, 500);
	})
};
  
window.onload = setTimeout(async function () {
    document.body.classList.add('loaded_hiding');
    
    let res = loaded();
    await res;
}, 2000)
```

можно вместо window.setTimeout просто писать setTimeout()
мы полностью выносим второй setTimeout в функцию loaded() которая возвращает промис
res это промис который возвращает функция и потом мы ее ждем await-ом

**Comment by Rokatoka** [comment]
https://github.com/Rrre-Gina/astro/issues/1#issuecomment-1112144010

думаю лучше оставить только 1 z-index: 1 для хэдера (еще можно background-color задать какой нить чтобы не прозрачный был) и в функции загрузки добавить/убрать хэдеру display: none

**Comment by Kuralbaev** [comment]
согласен :D

**Comment by Rrre-Gina** [comment]
> [#1 (comment)](https://github.com/Rrre-Gina/astro/issues/1#issuecomment-1112144010)
> 
> думаю лучше оставить только 1 z-index: 1 для хэдера (еще можно background-color задать какой нить чтобы не прозрачный был) и в функции загрузки добавить/убрать хэдеру display: none

Абылай решил оставить фон прозрачным, так как при цветном фоне меню перекрывет картинку первую и не очень смотрится. 
А остальное исправила, спасибо большое :)  Залила, можно чекать
